// Generated by CoffeeScript 1.7.1
(function() {
  window.whitetile.playingMusic = false;

  window.whitetile.backgroundMusic = new Audio("music.mp3");

  Zepto(function() {
    var playMusic, stopMusic;
    window.game = new window.whitetile.WhiteTile("#game-canvas");
    window.game.setup();
    window.game.start();
    window.whitetile.backgroundMusic.loop = true;
    playMusic = function() {
      window.whitetile.backgroundMusic.currentTime = 0;
      return window.whitetile.backgroundMusic.play();
    };
    stopMusic = function() {
      window.whitetile.backgroundMusic.pause();
    };
    window.whitetile.backgroundMusic.addEventListener("ended", function() {
      if (window.whitetile.playingMusic) {
        return playMusic();
      }
    });
    return $("#music-toggle").on("click", function() {
      window.whitetile.playingMusic = !window.whitetile.playingMusic;
      if (window.whitetile.playingMusic) {
        return playMusic();
      } else {
        return stopMusic();
      }
    });
  });

}).call(this);
